# # details={}
# # for i in range(10):
# #    n=input("enter name:")
# #    m=input("enter marks:")
# #    details[n]=m
# # print(details)

# a=int(input("enter any num"))
# def prime_num(a):
#   # a=int(input("enter any num"))
#   i=2
#   fact=1
#   while i<(a):
#         if a%i==0:
#           fact+=1
#         i=i+1
#   if fact<1:
#     print("prime")
#   # else:
#       # print("not prime")        
# prime_num(a)
# print(prime_num(a))

# a=[105,250,2501,200,1100]
# # c=[]
# i=0
# b=[]
# while i<len(a):
#       b=str(a[i])
#       if '0' in a:
#         b.append((a.replace("0"," ")))
#       i=i+1
# print(b)

# num_list={'a':10,'b':20,'c':30,'d':40}
# new_dict=current={}
# for name in num_list:
#     current[name]={}
#     current=current[name]
# print(new_dict)

# def fun(n):
#     n=int(input("enter any num"))
#     i=1
#     x=0
#     y=1
#     z=0
#     while i<=n:
#         print(z)
#         x=y
#         y=z
#         z=x+y
#         i=i+1
# fun(6)


                 
          
      